export const fakeNotifications = [
  {
    id: "1",
    title: "Scan Completed",
    message: "Your full scan for example.com has completed successfully.",
    type: "success",
    read: false,
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Critical Vulnerability Found",
    message: "A critical vulnerability was detected on 192.168.1.10.",
    type: "error",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
  },
  {
    id: "3",
    title: "New Domain Added",
    message: "The domain testsite.com was added to your assets.",
    type: "info",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: "4",
    title: "Scan Failed",
    message: "Scheduled scan for api.example.com failed to start.",
    type: "error",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: "5",
    title: "Subscription Expiring",
    message: "Your subscription will expire in 3 days.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: "6",
    title: "IP Asset Added",
    message: "New IP 10.0.0.5 was successfully added.",
    type: "success",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 90),
  },
  {
    id: "7",
    title: "High Severity Issue",
    message: "High severity issue detected on mail.server.com.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
  },
  {
    id: "8",
    title: "Scan Started",
    message: "Your scheduled scan for internal network has started.",
    type: "info",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 180),
  },
  {
    id: "9",
    title: "Port Open Detected",
    message: "Port 22 is open on 172.16.0.2.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 240),
  },
  {
    id: "10",
    title: "System Maintenance",
    message: "System maintenance scheduled for tonight at 2 AM.",
    type: "info",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 300),
  },
  {
    id: "11",
    title: "Domain Removed",
    message: "The domain oldsite.com was removed from your assets.",
    type: "info",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 360),
  },
  {
    id: "12",
    title: "Multiple Vulnerabilities Found",
    message: "5 medium severity issues were detected in the latest scan.",
    type: "warning",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 420),
  },
  {
    id: "13",
    title: "Scan Cancelled",
    message: "You have successfully cancelled the running scan.",
    type: "success",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 480),
  },
  {
    id: "14",
    title: "Unauthorized Access Attempt",
    message: "Multiple failed login attempts detected.",
    type: "error",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 540),
  },
  {
    id: "15",
    title: "Weekly Report Ready",
    message: "Your weekly security report is now available.",
    type: "success",
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 600),
  },
];
